[package]
name = "src-ui"
version = "0.1.0"
edition = "2021"

[dependencies]
leptos = { version = "0.8.3", features = ["nightly", "csr"] }

[dev-dependencies]
wasm-bindgen = { version = "0.2.100" }

[profile.release]
lto = true
strip = "symbols"
